name: "flake.lock: update inputs"

on:
  workflow_dispatch: # allows manual run
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: update flake.lock
        run: |
          nix --version
          nix flake update
      - name: create pull request
        id: update-flake
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "flake.lock: update"
          title: "flake.lock: update"
          body: "Automated flake.lock update."
          branch: "automation/flake-lock-update"
          delete-branch: true
      - name: auto-merge PR
        if: steps.update-flake.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.update-flake.outputs.pull-request-number }} \
            --squash --auto --delete-branch